version: '3'
services:
  app:
    ports:
      - "9999:9999"
    container_name: app
    build: ./
    command:
      - /bin/sh
    environment:
      - MONGODB_URI
      - PORT
    networks:
      container:
        aliases:
          - x.xyz.com
    stdin_open: true
    tty: true
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    networks:
      container:
        aliases:
          - mongo
    ports:
      - "27017:27017"

networks:
  container:

